# Generated by Django 5.1 on 2024-08-22 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_remove_eleve_matricule'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='matricula',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
