# Generated by Django 5.1 on 2024-08-22 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_eleve_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='matricula',
            field=models.CharField(default=True, max_length=12),
        ),
    ]
