# Generated by Django 5.1 on 2024-08-23 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_rename_eleve_students'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='matricula',
            new_name='matricule',
        ),
    ]
