# Generated by Django 5.1 on 2024-08-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(max_length=1)),
                ('matricule', models.CharField(max_length=20)),
                ('courses', models.CharField(max_length=15)),
                ('number', models.CharField(max_length=10)),
                ('ville', models.CharField(max_length=20)),
            ],
        ),
    ]
